### ISSUE TITLE
Optional child objects are always created when the object is created from the node manager

### ISSUE THREAD

**Issue by ipigust** [OPCFoundation/UA-ModelCompiler#103]
If I define a simple object type with one optional child object and define also one object of this type, the object is created correctly. But when I create the object inside my C# code of the node manager (at CreateAddressSpace), then the optional child object is always created (which I don't want). The cause is that the initialization string always contains code for the optional childs.

Excerpt from the ModelDesign.xml
```
<ObjectType SymbolicName="MyNamespace:TestType" BaseType="OpcUa:BaseObjectType" SupportsEvents="true">
	<Description>Test 1</Description>
	<Children>
		<Object SymbolicName="MyNamespace:OptionalChildObject" TypeDefinition="OpcUa:BaseObjectType" SupportsEvents="true" ModellingRule="Optional"/>
	</Children>
</ObjectType>
<Object SymbolicName="MyNamespace:TestSet" TypeDefinition="OpcUa:BaseObjectType">
	<Description>Contains all instances of Test objects</Description>
	<References>
		<Reference IsInverse="true">
			<ReferenceType>OpcUa:Organizes</ReferenceType>
			<TargetId>OpcUa:ObjectsFolder</TargetId>
		</Reference>
	</References>
</Object>
<Object SymbolicName="MyNamespace:TestObjectFromModel" TypeDefinition="MyNamespace:TestType">
	<References>
		<Reference IsInverse="true">
			<ReferenceType>OpcUa:Organizes</ReferenceType>
			<TargetId>MyNamespace:TestSet</TargetId>
		</Reference>
	</References>
</Object>
```

![image](https://user-images.githubusercontent.com/33345934/170271797-9b3a57a4-50b2-4d99-a10c-599b22456da2.png)

**Comment by opcfoundation-org** [comment]
Objects declared in the ModelDesign are well known objects with fixed NodeIds. All optional children are instantiated because a NodeId needs to be reserved for each optional child.

Create instances in code if you do not want optional children.
