### ISSUE TITLE
ModellingRule "ExposesItsArray"

### ISSUE THREAD

**Issue by ghettus** [OPCFoundation/UA-ModelCompiler#107]
Hi,
I instanced a Variable declared as one dimension array of dimension 20. I've tried to add the attributes ModellingRule="ExposesItsArray" but the Variable doesn't appear in the generated NodeSet2.xml.
I was hoping to see a Variable with 20 children named Variable[0], Variable[1] ... Variable[19].

Is that modelling rules not yet implemented?

Thanks

**Comment by opcfoundation-org** [comment]
The generated model only includes nodes which are always present or need a fixed NodeId assigned. The length of the array changes at run time so the component nodes need to be created at runtime.
