### ISSUE TITLE
Defining fixed Value for instances

### ISSUE THREAD

**Issue by ghettus** [OPCFoundation/UA-ModelCompiler#108]
Hi,

in my instance's declaration XML I want to define fixed values for some nodes: for example I want a Boolean Variable to be always "true".
I've tried to define the attribute "Value":
```
<Variable SymbolicName="MyModel:VarTest"  TypeDefinition="OpcUa:BaseDataVariableType" DataType="OpcUa:Boolean" 
 Value="true" />
```
Then, I've tried to define the element "Value":
```
<Variable SymbolicName="MyModel:VarTest"  TypeDefinition="OpcUa:BaseDataVariableType"  DataType="OpcUa:Boolean"  >
  <Value>true</Value>
</Variable>
```
In both case the build is succesfull but in my Nodeset2 there's no information about that "true" value.
Is this behavior not implemented? Or I'm doing it wrong?

I'd like to be able to define values for `<Property>` and `<DataType>` also.

Thanks

**Comment by opcfoundation-org** [comment]
The namespace for elements inside default values is define by the OPC UA XML Encoding. It is not the same as the UANodeSet schema. 
See xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd"
In https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/Opc.Ua.ModelCompiler/Design.v105/OpcUaDiModel.xml

**Comment by FabiusF** [comment]
Hello all,

I also have another question about defining values.
I would like to define a generic sensor object type in my model. In the object type I have the property "Unit", which I would like to define when I define my specific sensors in the model.

Thank you in advance
