### ISSUE TITLE
PropertyDesign Enum attributes don't get serialized

### ISSUE THREAD

**Issue by gregorvilkner** [OPCFoundation/UA-ModelCompiler#110]
In the simple model below, the Purpose attribute on the Object type gets serialized, but the ValueRank on the PropertyDesign attribute doesn't get serialized.

Any idea of how to fix this?

Kind regards,
Gregor

> ModelDesign md = new ModelDesign();
            md.Items = new NodeDesign[]
            {
                new ObjectTypeDesign()
                {
                    Purpose=DataTypePurpose.ServicesOnly,
                    Children=new ListOfChildren()
                    {
                        Items=new InstanceDesign[]
                        {
                            new PropertyDesign()
                            {
                                ValueRank=ValueRank.Array
                            }
                        }
                    }
                }
            };
            using (var writer = XmlWriter.Create(Console.OpenStandardOutput()))
            {
                var serializer = new XmlSerializer(md.GetType());
                serializer.Serialize(writer, md);
            }

**Comment by opcfoundation-org** [comment]
When serializing from auto generated classes to need to check if a "Specified" property exists and set it.
i.e. ValueRankSpecified = true;

**Comment by gregorvilkner** [comment]
`
new PropertyDesign()
{
    ValueRank=ValueRank.Array,
    ValueRankSpecified=true,
}
`

cool. that was easy. thanks a lot. #livesaver
