### ISSUE TITLE
How to set PropertyDesign DataType to "ua:String"

### ISSUE THREAD

**Issue by gregorvilkner** [OPCFoundation/UA-ModelCompiler#111]
In the snippet below, how do I set DataType for instance to get "ua:String"?
How do I add the ua namespace to the ModelDesign root, i.e. xmlns:ua="http://opcfoundation.org/UA/"  ?
Thanks a lot for your help.
Cheers, Gregor

```           
ModelDesign md = new ModelDesign();
md.Items = new NodeDesign[]
{
    new ObjectTypeDesign()
    {
        Purpose=DataTypePurpose.ServicesOnly,
        Children=new ListOfChildren()
        {
            Items=new InstanceDesign[]
            {
                new PropertyDesign()
                {
                    ValueRank=ValueRank.Array,
                    ValueRankSpecified=true,
                    // wanted: xmlns:ua="http://opcfoundation.org/UA/" with DataType="ua:String"
                    DataType=new XmlQualifiedName("String", "ua")
                }
            }
        }
    }
};
XmlWriterSettings settings = new XmlWriterSettings { Indent = true };
using (var writer = XmlWriter.Create(Console.OpenStandardOutput(), settings))
{
    var serializer = new XmlSerializer(md.GetType());
    serializer.Serialize(writer, md);
}
```

**Comment by opcfoundation-org** [comment]
XmlQualifiedName requires that pass in the URI - not the prefix. The serializer assigns the appropriate prefix.

**Comment by gregorvilkner** [comment]
Will it also add the namespace to the root?

**Comment by opcfoundation-org** [comment]
You have to set up namespace tables and pass them to the XmlWriter constructor if you want to guarantee that.

**Comment by gregorvilkner** [comment]
Could you provide or point to a sample?

I tried below:

```
DataType=new XmlQualifiedName("String", "http://opcfoundation.org/UA/")
```

which resulted in:

```
<Property xmlns:q1="http://opcfoundation.org/UA/" DataType="q1:String" ValueRank="Array" />
```

**Comment by opcfoundation-org** [comment]
This a .NET framework issue. You need to look at the Microsoft documentation.

**Comment by sixdiamants** [comment]
> Could you provide or point to a sample?
> 
> I tried below:
> 
> ```
> DataType=new XmlQualifiedName("String", "http://opcfoundation.org/UA/")
> ```
> 
> which resulted in:
> 
> ```
> <Property xmlns:q1="http://opcfoundation.org/UA/" DataType="q1:String" ValueRank="Array" />
> ```

Your XML writer is unaware of the prefix for namespace `http://opcfoundation.org/UA/` so the serialisation adds the full namespace to the XmlElement with a prefix q1. 
You should provide the serialiser with namespace `http://opcfoundation.org/UA/` and prefix "ua" like so:

```C#
XmlSerializerNamespaces xmlns = new XmlSerializerNamespaces(
	new XmlQualifiedName[] { new XmlQualifiedName(name: "ua", "http://opcfoundation.org/UA/") }
);
XmlWriterSettings settings = new XmlWriterSettings { Indent = true };
using (var writer = XmlWriter.Create(Console.OpenStandardOutput(), settings))
{
	var serializer = new XmlSerializer(md.GetType());
	serializer.Serialize(writer, md, namespaces: xmlns);
}
```
