### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by MaxCaulfield** [OPCFoundation/UA-ModelCompiler#112]
When I use this tool I get a NullReferenceException.
My Command Line is:
compile -d2 "..." -stack "..." -cg "..."

The cause seems to be the class ModelCompiler.NodeSetReaderSettings, which has a member NamespaceUris.
As far as I can see, this member is never set and the value is always null, however it is accessed in two places.

**Comment by opcfoundation-org** [comment]
Try updating your NuGet packages- that was an issue with the NETStandard library.

If that does not resolve the issue can you provide the exact command line.

**Comment by MaxCaulfield** [comment]
I updated but it did not resolve the issue.
This is my command line:
compile -d2 "somepath\opc.ua.fx.cm.nodeset2.xml" -stack "somepath\stack" -cg "somepath\identifiers.csv"

The NRE happens in the following line:
NodestToModelDesign.cs line 709:
NodeId importedNodeId = new NodeId(nodeId.Identifier, m_nsMapping[nodeId.NamespaceIndex]);

m_nsMapping is null, and IMO will always be null, because of that settings class I mentioned above.

![image](https://user-images.githubusercontent.com/15702884/184118779-1cdb5260-d3c6-404c-bef4-124f66da0e92.png)

**Comment by opcfoundation-org** [comment]
Try: 
 compile -version v105  -d2 ".\Opc.Ua.ModelCompiler\Design.v105\DemoModel.xml" -cg ".\Opc.Ua.ModelCompiler\CSVs\DemoModel.csv" -o2 ".\DemoModel\\" -useAllowSubtypes

**Comment by MaxCaulfield** [comment]
this command line works, thanks
I will try to figure out what the difference is

**Comment by opcfoundation-org** [comment]
The -stack option is only for use when generating the OPC UA service implementation code. It is not for use with normal information models. The help will be updated to indicate that it is for OPC Foundation use only.
