### ISSUE TITLE
Unable to clone submodule

### ISSUE THREAD

**Issue by Harmageddon** [OPCFoundation/UA-ModelCompiler#113]
I'm trying to build an executable on Windows, but already fail at the first step. When I clone with `git clone https://github.com/OPCFoundation/UA-ModelCompiler --recursive`, the main repo is cloned correctly, but the submodule "Stack" asks me for my credentials and fails to clone. 
Following the link here on GitHub, it gives me a 404 error: https://github.com/OPCF-Members/UA-.NETStandard-Prototypes/tree/8fc68e3fbcddcfa03da72a4734f625b94a82f49f

By the way, is there any source where I can get an already compiled executable or do I really need to go through compilation of the whole project to use it?

**Comment by opcfoundation-org** [comment]
Do not use the recursive flag when cloning.

The [ModelCompiler Solution.sln](https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/ModelCompiler%20Solution.sln) solution will build and run.

**Comment by Harmageddon** [comment]
Thank you for your quick reply! Without the recursive flag, it works. Maybe it would be helpful to update the documentation there?

But I'm still struggling with the compilation. I only have a license for VS 2015, which can't read the solution from the master branch. Following the opcua tutorial, I checked out 8817477c7b481fd6eb6e9cccc05b76e83c7329ba. This can be compiled with VS 2015, but I still get errors when compiling the XML:
```
Ein Teil des Pfades "D:\_Testprojekte\opc-ua\xml-result\FooFlt.Constants.cs" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append)
   bei Opc.Ua.ModelCompiler.ModelGenerator2.WriteTemplate_ConstantsSingleFile(String filePath, List`1 nodes) in D:\_Libraries\UA-ModelCompiler\ModelCompiler\ModelGenerator2.cs:Zeile 1872.
   bei Opc.Ua.ModelCompiler.ModelGenerator2.GenerateMultipleFiles(String filePath, Boolean useXmlInitializers, String[] excludedCategories, Boolean includeDisplayNames) in D:\_Libraries\UA-ModelCompiler\ModelCompiler\ModelGenerator2.cs:Zeile 130.
   bei Opc.Ua.ModelCompiler.Program.ProcessCommandLine2(List`1 tokens) in D:\_Libraries\UA-ModelCompiler\ModelCompiler\Program.cs:Zeile 449.
```

It would be really great to have precompiled binaries of stable versions of this compiler somewhere.

**Comment by opcfoundation-org** [comment]
VS 2015 is not supported. 
Please try the *free* version of VS2022: 
https://visualstudio.microsoft.com/vs/express/

**Comment by opcfoundation-org** [comment]
Updated the documentation.

**Comment by Harmageddon** [comment]
Okay, I got it to work with VS2022, using the PublishModel.bat script instead of the commands from the tutorial. Thank you for your help!
