### ISSUE TITLE
ForceEnumValues attribute is not working

### ISSUE THREAD

**Issue by supergaute** [OPCFoundation/UA-ModelCompiler#114]
It should be possible to use the ``ForceEnumValues`` attribute when defining an enum to force the ModelCompiler to generate EnumValues instead of EnumStrings.
This currently does nothing. The following code generates EnumStrings variables although it shouldn't:

	<opc:DataType SymbolicName="EnumTest" BaseType="Enumeration" ForceEnumValues="true">
		<opc:Fields>
			<opc:Field Name="A" Identifier="0" />
			<opc:Field Name="B" Identifier="1" />
		</opc:Fields>
	</opc:DataType>

By tricking the ModelCompiler and rearranging the enum fields, it will generate EnumValues variables:

	<opc:DataType SymbolicName="EnumTest" BaseType="Enumeration">
		<opc:Fields>
			<opc:Field Name="B" Identifier="1" />
			<opc:Field Name="A" Identifier="0" />
		</opc:Fields>
	</opc:DataType>

This goes to show that the ModelCompiler can do EnumValues correctly, but the ForceEnumValues attribute has no effect.

**Comment by supergaute** [comment]
This was tested with [sailavid/ua-modelcompiler](https://cloud.docker.com/u/sailavid/repository/docker/sailavid/ua-modelcompiler). docker image. When I clone repo and build, this is not an issue.

Perhaps time to update the docker image?

**Comment by opcfoundation-org** [comment]
Docker image has been updated in the member only beta:
https://github.com/OPCF-Members/UA-ModelCompiler/blob/master/Dockerfile
