### ISSUE TITLE
Model crashes when modeluri does not start with http://opcfoundation.org/UA/ and/or model uri is shorter than 28 chars.

### ISSUE THREAD

**Issue by maxschiffer** [OPCFoundation/UA-ModelCompiler#125]
The Modelcompiler crashes, when code for a model is generated thats uri does not start with http://opcfoundation.org/UA/ and/or model uri is shorter than 28 chars.

This is due to the implementation of the "private static Namespace CreateNamespace(ModelTableEntry model)" method in the [NodeSetToModelDesign.cs](https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/Opc.Ua.ModelCompiler/NodeSetToModelDesign.cs#L179)  file.
The method assumes all modeluris start with http://opcfoundation.org/UA/ and does a substring with the length of said uri (http://opcfoundation.org/UA/):

```
private static Namespace CreateNamespace(ModelTableEntry model)
        {
            var ns = new Namespace()
            {
                Name = model.ModelUri.Substring(Namespaces.OpcUa.Length).Replace("/", " ").Trim().Replace(" ", "."),
                Value = model.ModelUri,
                XmlNamespace = model.XmlSchemaUri,
                PublicationDate = model.PublicationDate.ToString("yyyy-MM-ddT00:00:00Z"),
                Version = model.Version
            };

            if (ns.Value == Opc.Ua.Namespaces.OpcUa)
            {
                ns.XmlNamespace = Opc.Ua.Namespaces.OpcUaXsd;
            }

            ns.XmlPrefix = ns.Prefix = "Opc.Ua." + ns.Name;
            ns.Name = ns.Name.Replace(".", "");

            if (ns.Value == Namespaces.OpcUa)
            {
                ns.Name = "OpcUa";
                ns.XmlPrefix = ns.Prefix = "Opc.Ua";
            }

            return ns;
        }
```

This could easily be fixed by adding a switchcase and just using the name supplied from the commandline.

`-d2 "<pathToNodeSet2.xml>,<Namespace.YourModel>,**<Name/Shortname>**" 
`
or implementing some logic like this:

```
private static Namespace CreateNamespace(ModelTableEntry model)
        {
            Namespace ns = null;
            if (model.ModelUri.StartsWith(Namespaces.OpcUa))
            {
                ns = new Namespace()
                {
                    Name = model.ModelUri.Substring(Namespaces.OpcUa.Length).Replace("/", " ").Trim().Replace(" ", "."),
                    Value = model.ModelUri,
                    XmlNamespace = model.XmlSchemaUri,
                    PublicationDate = model.PublicationDate.ToString("yyyy-MM-ddT00:00:00Z"),
                    Version = model.Version
                };
                ns.XmlPrefix = ns.Prefix = "Opc.Ua." + ns.Name;
                ns.Name = ns.Name.Replace(".", "");
            }
            else
            {
                ns = new Namespace()
                {
                    Name = model.ModelUri.Replace("http://", "").Replace("/", " ").Trim().Replace(" ", "."),
                    Value = model.ModelUri,
                    XmlNamespace = model.XmlSchemaUri,
                    PublicationDate = model.PublicationDate.ToString("yyyy-MM-ddT00:00:00Z"),
                    Version = model.Version
                };
                ns.XmlPrefix = ns.Name;
                ns.Name = ns.Name.Replace(".", " ");
            }

            if (ns.Value == Namespaces.OpcUa)
            {
                ns.Name = "OpcUa";
                ns.XmlPrefix = ns.Prefix = "Opc.Ua";
            }

            return ns;
        }
```

**Comment by opcfoundation-org** [comment]
Why don't you just fix the information model? It is a bad practice to have the same name for an output argument as an input argument. It is quite likely that doing so will cause issues or other code generators.

**Comment by maxschiffer** [comment]
If its bad practice, why not forbid it in the OPC specification?
Also there is no other way to implement a "ref" argument in OPC UA.

If for instance I'd like to request a specific Id/Name for something and pass it on to the method and the systems interal logic doesn't allow this or the name is already taken so it generates a new name/id and returns it. Instead of just throwing an error and having the client resubmit it.

I'll bring this up in the working group, but I still consider this a valid usecase.

What about the second, namespace related part of the PR?

**Comment by maxschiffer** [comment]
Pull request is now updated
https://github.com/OPCF-Members/UA-ModelCompiler/pull/23
