### ISSUE TITLE
What tool generates the xml and csv file

### ISSUE THREAD

**Issue by Cur001** [OPCFoundation/UA-ModelCompiler#13]
Unified Automation have a UAModeller tool is their a tool that is used by the UA-ModelCompiler to generate the xml and csv file that will ultimately be used to generate the C# code. Can i ask to be pointed in the direction of the tool that is used to generate the xml and csv files that are consumed by UA-ModelCompiler? 

UAModeller does not give me an xml file with the correct structure can you point me at what tool everyone is using in order to get xml in the correct format so UA-ModelCompiler can generate C#

thanks

**Comment by mpostol** [comment]
Try this:
http://www.commsvr.com/Products/OPCUA/UAModelDesigner.aspx
