### ISSUE TITLE
Well-known ModelDesign.xsd URL broken redirect

### ISSUE THREAD

**Issue by LaXiS96** [OPCFoundation/UA-ModelCompiler#131]
Hello,
the `http://opcfoundation.org/UA/ModelDesign.xsd` URL that is usually set as `xmlns:opc` in a model design XML file redirects to `https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/ModelCompiler/UA%20Model%20Design.xsd`, which is now a 404 page since the `ModelCompiler` folder has been renamed to `Opc.Ua.ModelCompiler`.
I believe this is breaking autocomplete and validation in VSCode, but I might be wrong.

Thank you

**Comment by randy-armstrong** [comment]
Should be fixed once your browser's cache is cleared.
