### ISSUE TITLE
PackML code generation wrong

### ISSUE THREAD

**Issue by eoursel** [OPCFoundation/UA-ModelCompiler#133]
Hi

I notice that the PackML ObjectType  PackMLBaseObjectType as defined in  https://reference.opcfoundation.org/PackML/v101/docs/6.3.2 in incorrectly generated by the model compiler when taking the official PackML NodeSet2 as input.  

All the Mandatory objects Admin, Status, BaseStateMachine are missing as well as the Methods defined on this object. 

The generated object type by the Model Compiler is 

`<UAObjectType NodeId="ns=1;i=6" BrowseName="1:PackMLBaseObjectType">
    <DisplayName>PackMLBaseObjectType</DisplayName>
    <References>
      <Reference ReferenceType="HasProperty">ns=1;i=221</Reference>
      <Reference ReferenceType="HasProperty">ns=1;i=218</Reference>
      <Reference ReferenceType="HasSubtype" IsForward="false">i=58</Reference>
    </References>
  </UAObjectType>`

while the NodeSet2 input of  the model compiler is

` <UAObjectType NodeId="ns=1;i=6" BrowseName="1:PackMLBaseObjectType">
    <DisplayName>PackMLBaseObjectType</DisplayName>
    <Documentation>https://reference.opcfoundation.org/v104/PackML/v101/docs/6.3.2</Documentation>
    <References>
      <Reference ReferenceType="HasComponent">ns=1;i=73</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=88</Reference>
      <Reference ReferenceType="HasSubtype" IsForward="false">i=58</Reference>
      <Reference ReferenceType="HasProperty">ns=1;i=221</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=403</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=404</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=400</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=402</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=401</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=362</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=87</Reference>
      <Reference ReferenceType="HasProperty">ns=1;i=218</Reference>
    </References>
  </UAObjectType>`

The problem is that the C# is also wrong. The point is that the Create method  which creates an instance of the PackMLBaseObjectType  is creating an incomplete instance albeit the type PackMLBaseObjectType  in the Types hierarchy looks ok with UaExpert. 

Regards

**Comment by opcfoundation-org** [comment]
The PackML has many Nodes without an absolute SymbolicName or a ParentNodeId.  As a result, it can't be used as an input to the ModelCompiler.  A mantis issue has been created: https://mantis.opcfoundation.org/view.php?id=8882

I am not sure how you got any output at all but I suspect it is because of a bug in the public version that has been fixed in the member-only version.

**Comment by eoursel** [comment]
@opcfoundation-org thanks. I must admit I had to add some symbolic names in the source nodeset in order to generate something. This is another issue. The problem here is the structure with the HasComponent reference which refer to an Object not a Variable or property. Agree with that?

**Comment by opcfoundation-org** [comment]
I fixed the NodeSet (added all of the missing ParentNodeIds).

[Opc.Ua.PackML.NodeSet2.xml.txt](https://github.com/OPCFoundation/UA-ModelCompiler/files/12062422/Opc.Ua.PackML.NodeSet2.xml.txt)

**Comment by opcfoundation-org** [comment]
Added fix to member-only version that handles missing ParentNodeIds if reverse references exist on the child.

**Comment by eoursel** [comment]
Thanks @randy-armstrong  It works perfectly with the member-only model compiler. Last point is  who is maintaining the PackML NodeSet? 

It should be updated since PackML is one of the CS which is really used for batch manufacturing. I agree this is what is described in the Mantis issue.

**Comment by opcfoundation-org** [comment]
See https://profiles.opcfoundation.org/workinggroup/38
