### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by FabiusF** [OPCFoundation/UA-ModelCompiler#138]
Hello everybody,
I hope I am posting my question in the right place. 
I am currently trying to create an information model for a heat pump. I have tried to derive the structure for the xml design file myself from the examples I could find on the internet. Unfortunately, that didn't work out so well. 
When compiling the design file for the heat pump, I get the following error: "[ArgumentNullException] Value cannot be null (Parameter 'key')". 
The two examples I found are both compiled without any problems.

Example 1: https://www.youtube.com/watch?v=gxA7SDNLHgc&list=PLIrJJXPVFRvjHsA9tta8yULOB8nPUO_G7&index=4
Example 2: https://github.com/OPCFoundation/UA-.NETStandard-Samples/blob/master/Samples/Opc.Ua.Sample/Boiler/BoilerDesign.xml

I have also tried a variant in which I have left out parts of the variables, but the same error comes out.
![grafik](https://github.com/OPCFoundation/UA-ModelCompiler/assets/102971882/4d536dcf-0257-40d7-b4d7-2c7b4cceefe4)

**Comment by Lemonbonbon** [comment]
Hello, I am trying the same and I get a similar error: [ArgumentException] The path is empty. (Parameter 'path') in the command window. I do not know how to solve this.

**Comment by FabiusF** [comment]
@Lemonbonbon, I just tried to compile the examples again and now I get an error with them too. Were you able to compile the 
example structures?
![grafik](https://github.com/OPCFoundation/UA-ModelCompiler/assets/102971882/57bf665b-7152-4a19-8868-41241a33621a)

**Comment by Lemonbonbon** [comment]
I tried the "DemoModel.xml" in the "\Opc.Ua.ModelCompiler\Design.v105". It does not work. I was able to get rid of the "[ArgumentException] The path is empty. (Parameter 'path')" error by downgrading the NuGet package in the UACompiler solution, but now I get a different error: "[ArgumentException] Invalid string NodeId without namespace index ('ns=')." Again, I do not know how to solve this.

**Comment by opcfoundation-org** [comment]
Pushed a fix.

**Comment by FabiusF** [comment]
Thanks @opcfoundation-org ,
I just cloned the repo and tried it out, it solved the second error. However, when I compile my model, I get the same error as at the beginning.
Is there a way to check the structure of my model in advance? 
![grafik](https://github.com/OPCFoundation/UA-ModelCompiler/assets/102971882/5df827e8-5081-418b-b5d8-176e67adbfab)

**Comment by opcfoundation-org** [comment]
Need the exact file you are using.

**Comment by FabiusF** [comment]
Sorry @opcfoundation-org 
for not getting back to you, but I had talked to my university supervisors again and rebuilt the model. Now my information model works. However, I still have a question, because I couldn't find an example for it. Could you show me how to load a specification into my model? 

Otherwise, thanks for your help

**Comment by opcfoundation-org** [comment]
What do you mean by 'load a specification into my model'?

**Comment by FabiusF** [comment]
My plan is to have my new objects descend from the DeviceType in my information model. Now the question is how do I specify the DeviceType correctly in the ModelDesign.xml?
![Unbenannt](https://github.com/OPCFoundation/UA-ModelCompiler/assets/102971882/2b977c18-ec1a-42fb-a0b8-7c6ebc99dfea)

**Comment by opcfoundation-org** [comment]
You want to reference the DI specification in the ModelDesign: 


```
<opc:Namespaces>
  <opc:Namespace Name="DemoModel" Prefix="DemoModel"  XmlNamespace="http://www.opcfoundation.org/DemoModel/Types.xsd"  XmlPrefix="DemoModel">http://www.opcfoundation.org/DemoModel/</opc:Namespace>
  <opc:Namespace Name="OpcUa" Prefix="Opc.Ua" Version="1.05.02" PublicationDate="2022-06-28T00:00:00Z" InternalPrefix="Opc.Ua.Server" XmlNamespace="http://opcfoundation.org/UA/2008/02/Types.xsd" XmlPrefix="OpcUa">http://opcfoundation.org/UA/</opc:Namespace>
  <opc:Namespace Name="DI" Prefix="Opc.Ua.Di" InternalPrefix="Opc.Ua.Di.Server" XmlPrefix="OpcUaDi">http://opcfoundation.org/UA/DI/</opc:Namespace>
</opc:Namespaces>
```

Add you must explicitly add the DI NodeSet as an additional -d2 argument

```
string[] args2 = {
    "compile",
    "-d2",
    @".\Design.v105\DemoModel.xml",
    "-d2",
    @"...\nodesets\v105\DI\Opc.Ua.Di.NodeSet2.xml",
    "-version",
    "v105",
    "-exclude",
    "Draft",
    "-c",
    @".\Opc.Ua.ModelCompiler\CSVs\DemoModel.csv",
    "-o2",
    @".\Tests\DemoModel\DemoModel"
};

```

**Comment by FabiusF** [comment]
I apologise for not getting back to you, but thank you very much it has now worked
