### ISSUE TITLE
OPC UA TMC Compiler Problem

### ISSUE THREAD

**Issue by bkadi** [OPCFoundation/UA-ModelCompiler#139]
I'm adding sub-references. I encounter this error when I run the program after DI and PackML.

[InvalidOperationException] SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_SubCarriers_SubCarrier_Data max recursion exceeded. Check model.

**Comment by opcfoundation-org** [comment]
This is bug because the Model has nodes that are parent and child of the same Node.
