### ISSUE TITLE
AccessLevel enumeration lacks entries for the purpose of HistoryWrite

### ISSUE THREAD

**Issue by sixdiamants** [OPCFoundation/UA-ModelCompiler#14]
The UA Model Design.xsd specifies that the AccessLevel type can adopt one of "none", "Read", "Write", "ReadWrite".
However, the OPC-UA specification, part 3, paragraph 8.57 also specifies fields HistoryRead (bit 2) and _HistoryWrite_ (bit 3) and some more.  The HistoryWrite bit 

> "Indicates if the history of the value is writable. It also indicates if the history of the Variable is available via the OPC UA Server."

I wish to activate historizing and would therefore want to activate HistoryRead and HistoryWrite. 

I'm aware of the "historizing" XML-attribute of the VariableTypeDesign. However, this would  implement the OPC-UA attribute "historizing" which indicates that (paragraph 5.6.2.) :

>  ...the Server _is actively collecting_ data for the history of the Variable. This differs from the AccessLevel Attribute which identifies if the Variable has any historical data. A value of TRUE indicates that the Server is actively collecting data 

Presently, my server refuses to historise data and I don't know how to activate it.

Yours,
Bob

**Comment by opcfoundation-org** [comment]
The ModelDesign file is for static information models. Values that are set at run time can be done in code.
