### ISSUE TITLE
Compiled Dotnet files are missing a definition

### ISSUE THREAD

**Issue by ChrisDahmen** [OPCFoundation/UA-ModelCompiler#155]
Hello, I am using the UA-ModelCompiler in the attempt to create a prototype OPC UA Server using NodeSet2 files from the [UA-Nodeset repository](https://github.com/OPCFoundation/UA-Nodeset/tree/latest). I am trying to compile the NodeSets using the following command:
````
.\Opc.Ua.ModelCompiler.exe compile-nodesets
  -input C:\Repos\TestSoftware\OpcUaServer\NodeSets\ 
  -o2 C:\Repos\TestSoftware\OpcUaServer\NodeSets\Generated\ 
  -uri http://opcfoundation.org/UA/Machinery/ 
  -uri http://opcfoundation.org/UA/IA/
  -uri http://opcfoundation.org/UA/DI/ 
  -uri http://opcfoundation.org/UA/MachineTool/
````

The resulting files look good at first sight, however upon compilation I am getting the following issue:
````
CS0117	'BrowseNames' does not contain a definition for 'MachineryBuildingBlocks'
OpcUaServer C:\Repos\TestSoftware\OpcUaServer\NodeSets\Generated\MachineTool\UAModel.MachineTool.Classes.cs	6181
````

This result was testet with both the current master branch [a366dea](https://github.com/OPCFoundation/UA-ModelCompiler/commit/a366deaeec526b3421873b2d16fc5e36369c8fe0) aswell as the 2.3.0 release tag.

Thanks for the help in Advance.

**Comment by opcfoundation-org** [comment]
This is a known issue that requires an update to the Machinery nodeset.
PLease manually add the missing constant.

**Comment by ChrisDahmen** [comment]
Allright thanks.
