### ISSUE TITLE
XML Schema Explorer

### ISSUE THREAD

**Issue by sntechno** [OPCFoundation/UA-ModelCompiler#18]
Are there any sources of help or tutorials on using the XML Schema Explorer available?

**Comment by opcfoundation-org** [comment]
XML Schema Explorer is a Visual Tool. 
The documentation for the input schema is in the "UA Model Design.xsd".
An example of model created with the tool is here:
https://github.com/OPCFoundation/UA-.NETStandard/tree/master/SampleApplications/Workshop/Boiler/Server

**Comment by pasquale90** [comment]
Could you please update the link? Thanks
