### ISSUE TITLE
OverflowException for enum

### ISSUE THREAD

**Issue by ancapaul** [OPCFoundation/UA-ModelCompiler#183]
I tried to add the following field to an enum:

<opc:Field Name="Invalid" Identifier="2147483648"/>

But I'm getting the following error:

[InvalidOperationException] There is an error in XML document (35, 33).
>>> [OverflowException] Value was either too large or too small for an Int32.

I don't see why this should happen the min and max of a 32 bit int should be -2147483648 and 2147483647.

**Comment by opcfoundation-org** [comment]
It is out of range: 2147483648 > 2147483647

**Comment by ancapaul** [comment]
🤦
