### ISSUE TITLE
How to define 64bit Enum

### ISSUE THREAD

**Issue by ancapaul** [OPCFoundation/UA-ModelCompiler#184]
Hello,

Is it possible to define a 64 bit enumeration in the model compiler?

**Comment by opcfoundation-org** [comment]
If you think you need an 64 bit value you should not be using an Enumeration to model it.
An Enumeration is NOT a bit field. It is a finite set of named values.
If you have a bit field you should be using an OptionSet.

**Comment by ancapaul** [comment]
Thanks for the answer I will have a look at optionset.
