### ISSUE TITLE
Core library functionality

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-ModelCompiler#2]
The local library [Core](https://github.com/OPCFoundation/UA-ModelCompiler/tree/master/Core) contains functionality not required by the compiler. It seems similar to the library [Core](https://github.com/OPCFoundation/UA-.NET/tree/master/Stack/Core) included in the project OPCFoundation/UA-.NET. It causes code synchronization and maintenance issues. We have also problem with license compatibility.
Proposal:
- decouple the projects by creating a common component for the stack and compiler to be maintained separately;
- cerate Nuget package that will be added to both projects.
- the package should have compatible license.

**Comment by tornadocean** [comment]
submodule update for local library Core, but not find the repository.

Cloning into 'CertificateGenerator/stack'...
remote: Repository not found.
fatal: repository 'https://github.com/OPCFoundation/UA-AnsiC/' not found
Clone of 'https://github.com/OPCFoundation/UA-AnsiC' into submodule path 'CertificateGenerator/stack' failed

**Comment by SparhawkSoftware** [comment]
The Core library only exists because of the primitive type definitions (e.g. Variant) and to provide a means to test the auto-generated code.

It should NOT be linked to the UA-.NET library.
That is why its name has been changed to 'Opc.Ua.ModelCompiler.Core'.
