### ISSUE TITLE
Default Values in Model Compiler instances

### ISSUE THREAD

**Issue by drtoad** [OPCFoundation/UA-ModelCompiler#22]
How can I set the Value attribute of an object type I define in a model xml file?

I am using the Model Compiler to create Object Types which contain hierarchies including Variables, I would like to set the Value on the object instances based on the model. I am setting DefaultValue in the model. When instantiating the object and initializing with NodeState.Create, Value does not get set. Should it be set to DefaultValue? Is there some way to set Value from the model? It seems to be prevented from the initialization string. Is there something I am missing?

(Moving this issue here from the UA-.NETStandard repository as requested.)

**Comment by sixdiamants** [comment]
I works out that one can create an instance with a default value.  
Note that the below Model Design instantiates an object of type Zentralelement. I then add a property called `Bereich` with default value 2 to this new instance.  The objecttype doesn't define the property `Bereich`. 

`  
<opc:Object TypeDefinition='Zentralelement' SymbolicName="CR__5106__H">   

    <opc:BrowseName>Zentralelement CR_5106_H </opc:BrowseName>  

    <opc:Children>  

      <opc:Property SymbolicName="Bereich">  

        <opc:Description>Nummer des Rechners</opc:Description>  

        <opc:DefaultValue>   
          <uax:Byte>2</uax:Byte>  
        </opc:DefaultValue>  
...
`
