### ISSUE TITLE
option to create string instead of numeric NodeId 

### ISSUE THREAD

**Issue by sixdiamants** [OPCFoundation/UA-ModelCompiler#23]
The model compiler by default generates a Predefined Nodes XML file where NodeIds have numerical identifiers like so 
`<uax:Identifier>ns=1;i=15301</uax:Identifier>`.

I have a use case for string identifiers like 
`<uax:Identifier>ns=1`**;s=myThing**`</uax:Identifier>`

Now, the model design XML file offers a StringId attribute element but this doesn't produce a string nodeId. I would suggest that use of this attribute produce a nodeId with string identifier rather than a numeric identifier.

Bob

**Comment by edo13em** [comment]
Hi! I am trying to do the same thing but I can't figure out how to do it. 
The only way I have found is to modify directly the PredefinedNodes.xml compiled by the compiler. Have you found a easier solution? Can you help me please?
Edo

**Comment by opcfoundation-org** [comment]
Not supported at this time and it would probably take a lot of work chasing all of the side effects.

**Comment by andreacamera** [comment]
Hello everyone, I am trying to generate NodeId in GUID (;g=".....") format, is this function not yet available?

Thank you in advance

**Comment by xujiesh0510** [comment]
hi ,@andreacamera . i figured out how to create string nodeid like  "ns=1;i=mynodeid" 
step 1:  Opc.Ua.ModelCompiler.exe compile -d2 modeldesign.xml  -cg model.csv -o2 targetfolder
this will generate a model.csv file  , then modify model.csv ,make sure  id in  each line is string format 
for example 
CustomEvent_Message,"r10d",Variable
CustomEvent_Severity,"guid whatever you like ",Variable

step 2  Opc.Ua.ModelCompiler.exe compile -d2 modeldesign.xml  -c model.csv -o2 targetfolder
this will generate  BatchPlant.NodeSet2.xml with string nodeid

**Comment by andreacamera** [comment]
Thank you very much. This partially solves my problem, i tried it and it is very useful because now I can generate NodeId as "s=...guid...." and afterwards replace s= with g=. Does anyone know if it is possible to generate g= directly? Thank you.

**Comment by janvhagen** [comment]
it doesn't really work for me the compiler also generates 2 extra classes for me constant.cs datatypes.cs and the normal Classes.cs if i run it with : .\Opc.Ua.ModelCompiler.exe -d2 C:\Models\ModelDesign .xml -cg C:\Models\ModelDesign.csv -o C:\Models -console -version v104 it works but this is with Node id numeric and not a string . Am I missing something
