### ISSUE TITLE
Could not find the file "MeasurementUnits.cs"

### ISSUE THREAD

**Issue by XiaXuecun** [OPCFoundation/UA-ModelCompiler#24]
I download the  zip file,and openthe extracted folder,there's no file "MeasurementUnits.cs ",and I can't compile the project,can you give any help?

**Comment by matealex** [comment]
Can confirm this. Also, when opening the project in VS it shows that "packages.config" file from UA Model Compiler project is also missing along with other referenced components: "Csv", "CsvHelper" and "QuantityTypes"

**Comment by cerela82** [comment]
can't compile the project. missing files are: MeasurementUnits.cs, csv , CsvHelper and QuantityTypes.

**Comment by opcfoundation-org** [comment]
Should be fixed,
