### ISSUE TITLE
Parsing Error in XML File

### ISSUE THREAD

**Issue by adeel1996** [OPCFoundation/UA-ModelCompiler#26]
I am new to OPC-UA. I have created basic XML file for the following hierarchy but I am getting parsing Error can you please identify my mistake. 
(Nodes Hierarchy )
Plant
    Line Number
        Sensor1
            Voltage A
            Voltage B

Following is my XML code.

`<?xml version='1.0' encoding='utf-8'?>
<UANodeSet xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd" xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamespaceUris>
    <Uri>http://opcfoundation.org/UA/Sensor/</Uri>
  </NamespaceUris>
  <Aliases>
    <Alias Alias="Float">i=10</Alias>
    <Alias Alias="Organizes">i=35</Alias>
    <Alias Alias="HasTypeDefinition">i=40</Alias>
    <Alias Alias="HasProperty">i=46</Alias>
  </Aliases>
  <UAObject BrowseName="0:Plant" NodeId="i=20001" ParentNodeId="i=85">
    <DisplayName>Plant</DisplayName>
    <Description>Plant</Description>
    <References>
      <Reference IsForward="false" ReferenceType="Organizes">i=85</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=61</Reference>
      <Reference ReferenceType="Organizes">i=20002</Reference>
    </References>
  </UAObject>
  <UAObject BrowseName="0:LineNumber" NodeId="i=20002" ParentNodeId="i=20001">
    <DisplayName>LineNumber</DisplayName>
    <Description>LineNumber</Description>
    <References>
      <Reference IsForward="false" ReferenceType="Organizes">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=61</Reference>
      <Reference ReferenceType="Organizes">i=20003</Reference>
    </References>
  </UAObject>
  <UAObject BrowseName="0:Sensor1" NodeId="i=20003" ParentNodeId="i=20002">
    <DisplayName>Sensor1</DisplayName>
    <Description>The base type for all object nodes.</Description>
    <References>
      <Reference IsForward="false" ReferenceType="Organizes">i=20002</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=58</Reference>
      <Reference ReferenceType="HasProperty">i=20004</Reference>
      <Reference ReferenceType="HasProperty">i=20005</Reference>
    </References>
  </UAObject>
  <UAVariable BrowseName="0:VoltageA" DataType="Float" NodeId="i=20004" ParentNodeId="i=20003">
    <DisplayName>VoltageA</DisplayName>
    <Description>VoltageA</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasProperty">i=20003</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=68</Reference>
    </References>
    <Value>
      <uax:Float>9.99</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:VoltageB" DataType="Float" NodeId="i=20005" ParentNodeId="i=20003">
    <DisplayName>VoltageB</DisplayName>
    <Description>VoltageB</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasProperty">i=20003</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=68</Reference>
    </References>
    <Value>
      <uax:Float>9.99</uax:Float>
    </Value>
  </UAVariable>
</UANodeSet>
`

I will also attach screenshot of error message I am getting.
![parsingerror](https://user-images.githubusercontent.com/24505313/49202322-0c493a80-f3c6-11e8-8c8e-3424bac057f6.png)

**Comment by sixdiamants** [comment]
The model compiler can indeed produce XML that doesn't validate. The presence of spaces and dashes could for instance cause parsing errors. You may have to replace 

`Sensor-1`
by 
`Sensor_1`

**Comment by adeel1996** [comment]
@sixdiamants there is no '-' or '_' in xml file. I have used 'sensor1'. it was my mistake I write 'sensor-1' when writing hierarchy in description.

**Comment by NichtEuler** [comment]
It seems like the input xml must be a ModelDesign and not a NodeSet2.xml.

**Comment by opcfoundation-org** [comment]
Yes - the ModelDesign is the input. The UANodeSet is the output.
The ModelDesign schema is design for humans that manually edit.
The UANodeSet is machine readable.
