### ISSUE TITLE
ValueRank serialization works incorrectly

### ISSUE THREAD

**Issue by saurla** [OPCFoundation/UA-ModelCompiler#27]
The Save and GetAttributesToSave methods of BaseVariableState and BaseVariableTypeState won't serialize ValueRank if it's value is -2 (Any). This causes Update method to not initialize ValueRank at all, leaving it's value to default int value 0 (OneOrMoreDimensions). This can be fixed by omitting ValueRank from the serialization if it's value is 0 (OneOrMoreDimensions) instead of -2 (Any).

This issue causes invalid initialization strings for types which default ValueRank is Any when generating Opc.Ua.Classes file.

**Comment by opcfoundation-org** [comment]
Fixed.
