### ISSUE TITLE
What happened to UA-TypeRepository

### ISSUE THREAD

**Issue by turnerth** [OPCFoundation/UA-ModelCompiler#29]
Hi, I am from GE, one of the members of OPCFoundation. 

Last week there was a Repo called UA-TypeRepository.  I was using the README's to learn OPCUA hierarchy.

Where did it go?  Can you bring it back?

**Comment by opcfoundation-org** [comment]
It was made private while it is being developed.
The public pages are still available: https://opcfoundation.github.io/UA-TypeRepository/
