### ISSUE TITLE
Why switch default Value for Boolean

### ISSUE THREAD

**Issue by jooooogi** [OPCFoundation/UA-ModelCompiler#30]
in the methode GetDefaultValue by default false is used for the nullable bool, but then "true" is returned as default value.

https://github.com/OPCFoundation/UA-ModelCompiler/blob/647dda275e84886c475e8b39ad7790fbb569c0db/ModelCompiler/ModelGenerator2.cs#L4619

**Comment by opcfoundation-org** [comment]
While this is technically a bug the potential to break existing code by changing the default value in autogenerated code is very large so it will not be fixed.
