### ISSUE TITLE
[Feature Request] UA-ModelCompiler as Net Standard Project

### ISSUE THREAD

**Issue by lufthaens** [OPCFoundation/UA-ModelCompiler#31]
UA-ModelCompiler should be available as .Net Standard Project referencing the already existing Opc Ua Core Standard Project. Is there a possibility to implement that any time soon?

**Comment by opcfoundation-org** [comment]
The Core library has mods specific to the ModelCompiler and will likely never be migrated.
The library is Opc.Ua.ModelCompiler.Core.dll to reflect the fact that it is branch.
