### ISSUE TITLE
TypeDefinition for Method node

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-ModelCompiler#35]
The ModelDesign schema is used as the syntax definition of a language used to represent the UA Information Model. Each language must have also semantics definition that couples together the meaning (knowledge how to apply the text) and syntax constructs.  Someone could say that the spec is a good description of the semantics.  Partially it is true, but how to learn using the spec what it means TaypeDefinition attribute for the  Method element in the example below:

```xml
          <Method SymbolicName="ADI:SetConfiguration" TypeDefinition="ADI:AnalyserDeviceTypeSetConfigurationMethodType">
            <Description>Write the complete configuration of the AnalyserDevice and all of its components to the analyzer server and make the new configuration active.</Description>
          </Method>
```

From my experience, I know that it is required for the compiler to generate arguments and return value.

FYI, the topic model life-cycle is covered by the section of my ebook available for free:

[Address Space Model Life-cycle](https://commsvr.gitbook.io/ooi/semantic-data-processing/informationmodelsdevelopment/informationmodellifecycle)

It seems there are the following options:

1. Make the compiler and its entry language compliant with the specification (not sure but it could be hard task)
2. Provide an additional description of this language specification (should be included in the specification) - we discussed this topic many years - consider revisiting it. 

The precise definition of the compiler language is important for the recovery process (disassembly) based on the UANodeSet in case the UANodeSet xml file must be customized. In other words, the recovery process makes sense only in the case we know the target we are going to restore. 

I will appreciate any your opinion.

**Comment by opcfoundation-org** [comment]
Sorry for the late reply.

The ModelDesign scheme has been left out of the spec intentionally because we wanted on one normative representation of models. The code here should be treated as sample code.

**Comment by mpostol** [comment]
My concern is that if we have one normative model representation it shall be used to represent all model definitions, e.g. DI, ADI, PROFIBUS, etc. Why this representation is not used in the companion spec. Why we are using tables. As you said it is  NORMATIVE and UNIVERSAL representation.  The answer is very simple because IT IS IMPOSSIBLE. 

It is impossible because we have:

- language in
- language out

and they represent different information, so they must have different syntax and semantics. If we have to use two languages it is impossible to have one normative. It is contradictory! In other words, the compiler is not just a converter.

Additionally, the compiler produces something that cannot be modified manually, so the question is how to get back. I have just proved that decompilation is impossible in a generic case for many reasons.

BTW, we are not discussing the code, we are discussing the assumption: `we wanted on one normative representation of models`.  In Part 3 Annex 3 Graphical Notation we have another one and it is also NORMATIVE, so we have at least two NORMATIVE model representation. 

Probably saying that "it is sample code" you mean that it is a wrong place to discuss the strategy of the spec further development and you are right, so I am closing this thread. If you don't mind I will refer to this discussion in my derived work. I assume that now and here we can do nothing about this. 

Many thanks for your time and possibility to exchange our opinions. I really appreciate.
Mariusz
