### ISSUE TITLE
Correct docker container link

### ISSUE THREAD

**Issue by Pro** [OPCFoundation/UA-ModelCompiler#40]
@randy-armstrong thanks for merging #36 

After that it would make sense that you enable automated docker container builds for your own OPCF account. Otherwise the Readme still links to my docker builds:
https://github.com/OPCFoundation/UA-ModelCompiler/blame/master/README.md#L34

Its very easy and can be done in 5 minutes.
1. Create a personal account for you
2. Create a new organization on docker cloud: https://hub.docker.com/orgs `OPCFoundation` would make sense here as a name
3. Create a new repository `UA-ModelCompiler`
4. Link that docker repo to the github repo: https://docs.docker.com/docker-hub/builds/link-source/
5. Enable automated builds or just use the settings below: https://docs.docker.com/docker-hub/builds/

Here are the Settings I'm using, you can just use the same and you are done:

Branch: master
Tag: latest

![image](https://user-images.githubusercontent.com/251973/70308759-3ff64600-180c-11ea-9b9b-f17b80d85fa2.png)

6. Update the readme link
7. Just push to your repository, and it will automatically build a new docker container

You can also contact me directly if you have further issues or if I can support you in that direction
https://opcua.rocks/contact/

**Comment by opcfoundation-org** [comment]
The OPC-F has a policy to not provide pre-compiled binaries for code made available as samples. 
The link to your docker image is fine. 
You will obviously need to help anyone who has problems with it.
