### ISSUE TITLE
[question] How to ModelCompile v105 nodeset + own model?

### ISSUE THREAD

**Issue by awol-o** [OPCFoundation/UA-ModelCompiler#42]
The **BuildStandardTypes.bat** uses **ModelCompiler.Design.v104**. Commit **Fix 1.04 vs 1.05 duplication** includes removal of the **ModelCompiler.Design** folder and defaulting to v104 for **BuildStandardTypes.bat**. The **master** branch of **UA-Nodeset** is v1.05 according to the **readme.md** so where is the **Design.v105** folder used to create this or am I missing something? I wanted to check before doing something stupid like recreating the design folder by extracting the files from the **UA-Nodeset** repository and stripping out copyrights info added by scripts.

**Comment by awol-o** [comment]
I've added a pull request to fix an issue when trying to `BuildStandardTypes.bat "" "" 'all'` but now I know *v104* is output to a folder named 'master' which is probably associated on the build server with the **master** branch of **UA-Nodeset**. This could mean that **UA-Nodeset** is _not v1.05_ as stated in the **readme.md**. 

I was originally wanting the latest versions of nodesets and model compiler code to make sure my dependences are up to date because I am having issues with my code. However, in addition to not knowing how to get v105, I am comfused about the issues below which mean I am not sure I have the latest versions. 

**UA-Nodeset/DI/Opc.Ua.Di.Classes.cs** in the **master** branch, latest commit (9d8d9e7) is 8 months old, and cannot compile as per issue Nodeset Issue[#19](https://github.com/OPCFoundation/UA-Nodeset/issues/19)  (6 Feb) and Nodeset Issue[#41](https://github.com/OPCFoundation/UA-Nodeset/issues/41) (5 Sep). It would be a useful reference for me if the compiled code was up-to-date but these issues were closed and suggesting recompiling with the latest model compiler

However, these issues are still present with the latest ModelCompiler build (b1474b7). If the Mantis bug [4714](https://apps.opcfoundation.org/mantis/view.php?id=4714) has been applied to the master branch then a freshly compiled nodeset should not have this issue, and it does.

**Comment by awol-o** [comment]
Added a commit to my [pull request](https://github.com/OPCFoundation/UA-ModelCompiler/pull/43) that fixes issue in the **Opc.Ua.Di.Classes.cs** so it now compiles. My question still remains: how to compile my own model, that depends on DI, to v1.05 nodeset version?

**Comment by opcfoundation-org** [comment]
Fixed in next commit.
