### ISSUE TITLE
Enumerations

### ISSUE THREAD

**Issue by martinslezak** [OPCFoundation/UA-ModelCompiler#44]
Hello, we're using UA-ModelCompiler and actually we're solving issues with Enumerations.

Here's our XML description, focus on 
- opc:DataType TestEnum
- opc:Method TestVoidEnumMethodType
- opc:Variable testEnum
- opc:Method TestVoidWithEnum

```
<opc:DataType SymbolicName="TestEnum" BaseType="ua:Enumeration">
  <opc:Fields>
    <opc:Field Name="State1" Identifier="1" Value="1"></opc:Field>
    <opc:Field Name="State2" Identifier="2" Value="2"></opc:Field>
    <opc:Field Name="State3" Identifier="3" Value="3"></opc:Field>
    <opc:Field Name="State4" Identifier="4" Value="4"></opc:Field>
    <opc:Field Name="State5" Identifier="5" Value="5"></opc:Field>
  </opc:Fields>
</opc:DataType>
...
<opc:Method SymbolicName="TestVoidEnumMethodType">
  <opc:Description>test method</opc:Description>
  <opc:InputArguments>
    <opc:Argument Name="testEnum" DataType="TestEnum"> </opc:Argument>
  </opc:InputArguments>
</opc:Method>
...
<opc:ObjectType SymbolicName="PluginExample" BaseType="CpiServerDeviceBaseType">
  <opc:Description>Description from model.txt for PluginExample</opc:Description>
  <opc:Children>
    <opc:Object SymbolicName="ExampleObject" TypeDefinition="ExampleObjectType" SupportsEvents="true" MinimumSamplingInterval="500">
      <opc:DisplayName>ExampleObject</opc:DisplayName>
    </opc:Object>
    <opc:Variable SymbolicName="testString" DataType="ua:String" MinimumSamplingInterval="1000" AccessLevel="ReadWrite"></opc:Variable>
    <opc:Variable SymbolicName="testInt" DataType="ua:Int32" MinimumSamplingInterval="1000" AccessLevel="ReadWrite"></opc:Variable>
    <opc:Variable SymbolicName="testLong" DataType="ua:Int64" MinimumSamplingInterval="1000" AccessLevel="ReadWrite"></opc:Variable>
    <opc:Variable SymbolicName="testDouble" DataType="ua:Double" MinimumSamplingInterval="1000" AccessLevel="ReadWrite"></opc:Variable>
    <opc:Variable SymbolicName="testEnum" DataType="TestEnum" AccessLevel="ReadWrite" MinimumSamplingInterval="500"></opc:Variable>
    <opc:Property SymbolicName="arrayOfInt" DataType="ua:Int32" ValueRank="Array" AccessLevel="Read" MinimumSamplingInterval="500"/>
    <opc:Method SymbolicName="Test"  TypeDefinition="ExampleTestMethodType"  ModellingRule="Optional"></opc:Method>
    <opc:Method SymbolicName="TestVoidStringMethod"  TypeDefinition="TestVoidStringMethodType"  ModellingRule="Optional"></opc:Method>
    <opc:Method SymbolicName="TestVoidVoidMethod"  TypeDefinition="TestVoidVoidMethodType"  ModellingRule="Optional"></opc:Method>
    <opc:Method SymbolicName="TestVoidWithEnum" TypeDefinition="TestVoidEnumMethodType"  ModellingRule="Optional"></opc:Method>
  </opc:Children>
</opc:ObjectType>
```

This leads to defining new enum type:
![image](https://user-images.githubusercontent.com/21122279/70993243-e1fb1580-20cb-11ea-81c0-06bc0e9be244.png)

![image](https://user-images.githubusercontent.com/21122279/70993061-76b14380-20cb-11ea-91ce-b995c5e2d982.png)

First issue is with Variable testEnum:
![image](https://user-images.githubusercontent.com/21122279/70991381-a3635c00-20c7-11ea-8333-ac5f82dfa6df.png)
I supposed that it should be Enum type, so changing value should suggest combobox with enum values or something like that.
But nevermind, this is not critical.

Second and for our purpose critical issue is method with enum argument:
![image](https://user-images.githubusercontent.com/21122279/70991570-02c16c00-20c8-11ea-87b5-b4871b01d507.png)

Argument is again filled with number (no combobox) and what's more whole method can't be invoked, because UA Expert "Could not convert argument 0 to variant type TestEnum".

Are we missing something?
I would be glad for any help or point to correct this.

Thank You
Martin

**Comment by opcfoundation-org** [comment]
Enumerations are always read/written as Int32 values. The server should expect that Int32 is sent on the wire when validating the method arguments. It is not clear why it is failing.

Can you determine what datatype the server actually receives?
