### ISSUE TITLE
How to add "HasDescription" reference to a DataType?

### ISSUE THREAD

**Issue by jcbastosportela** [OPCFoundation/UA-ModelCompiler#50]
I am currently trying to create an information model using UA-ModelCompiler. When I create my own Structured DataType I see that in the generated NodeSet file is preventing the FreeOPC-UA https://github.com/FreeOpcUa/python-opcua server to be able to get an "object" of that type (`get_ua_class`). When I create the same DataType using UAModeler it works.

After comparing and hacking into the NodeSet files I found that the reason for that is the missing `HasDescription` reference on the Types>DataTypes>OPC Binary>[NAMESPACE_DIC]>[DATA_TYPE]

```xml
  <UAVariable NodeId="ns=1;i=15013" BrowseName="1:versionDataType" ParentNodeId="ns=1;i=15009" DataType="String">
    <DisplayName>versionDataType</DisplayName>
    <References>
      <Reference ReferenceType="HasTypeDefinition">i=69</Reference>
      <!-- added manually start... -->
      <Reference ReferenceType="HasDescription" IsForward="false">ns=1;i=15008</Reference>
      <!-- ... added manually end  -->
      <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=15009</Reference>
    </References>
    <Value>
      <String xmlns="http://opcfoundation.org/UA/2008/02/Types.xsd">versionDataType</String>
    </Value>
  </UAVariable>
```
where `ns=1;i=15008` is the DeafultBinary Object.

When I manually set it it works.

'''So my question is: what is necessary to make in the ModelDesign in order to get that reference?'''

regards

**Comment by opcfoundation-org** [comment]
The NodeSet generator reduces the size of the XML file by eliminating redundant information. In this case the HasDescription is on the encoder and it is up to the application reading the file to insert in the inverse reverse when it loads the NodeSet.

This behavior is described in Part 6:
https://reference.opcfoundation.org/v104/Core/docs/Part6/F.3/

> A UANodeSet is expected to contain many UANodes which reference each other. Tools that create UANodeSets should not add Reference elements for both directions in order to minimize the size of the XML file. Tools that read the UANodeSets shall automatically add reverse references unless reverse references are not appropriate given the ReferenceType semantics. HasTypeDefinition and HasModellingRule are two examples where it is not appropriate to add reverse references.
