### ISSUE TITLE
Wrong command line help for `-cg`

### ISSUE THREAD

**Issue by cactuaroid** [OPCFoundation/UA-ModelCompiler#51]
https://github.com/OPCFoundation/UA-ModelCompiler/blob/c57e4580cf961ef8b593b1e6e4c3637441c62804/ModelCompiler/HelpFile.txt#L8

The only difference between `-c` and `-cg` is that `-c` throws an exception if the specified CSV file is not found. `-cg` reads the specified CSV if exists as well as `-c`. "instead of reading it" is wrong. Please improve the explanations.

**Comment by opcfoundation-org** [comment]
Manually added to:
https://github.com/OPCF-Members/UA-ModelCompiler/commit/a89140db494cd99e1ebe935d6a82d890912f1250
Will merge to public repo in the next week or so.

**Comment by opcfoundation-org** [comment]
Old issue.
