### ISSUE TITLE
How to use DataTypes specified in Companion Specification

### ISSUE THREAD

**Issue by chhitz** [OPCFoundation/UA-ModelCompiler#53]
I need to use a Structure Data Type defined in a 3rd party companion specification in my model. The companion specification is available as NodeSet2.xml file.

I have declared the companion specification as an additional namespace in my model but I still get an error form the model compiler:

`The DataType reference for node My_Node is not valid: CustomDataType.`

How can I use the custom DataType in my Model. The goal is to generate a Nodeset2.xml file.

**Comment by opcfoundation-org** [comment]
The tool looks in the same directory as target ModelDesign for any design files which are referenced,

Do you have a design file and CSV for CustomDataType?
