### ISSUE TITLE
How to use the software

### ISSUE THREAD

**Issue by kksi0227** [OPCFoundation/UA-ModelCompiler#54]
Don't understand how to use this software, do you have instructions

**Comment by mpostol** [comment]
Hi @kksi0227 

- to get general information related to the topic check out the chapter of the book [Information Models Development](https://commsvr.gitbook.io/ooi/semantic-data-processing/informationmodelsdevelopment)
- the compiler is embedded as a plug-in in the open-access tool [OOI Address Space Model Designer (OOI ASMD)](https://github.com/mpostol/ASMD#ooi-address-space-model-designer-ooi-asmd)
- The answer `how to use the compiler` check out the help documentation [Model Build](https://commsvr-com.github.io/Documentation/ModelDesigner/html/420d7d38-cc1d-4de2-8718-0b5bb9222088.htm)

Hope it helps

**Comment by kksi0227** [comment]
he UA Model Designer cannot be downloaded from the corresponding url

**Comment by kksi0227** [comment]
你可以写一个对应的Demo吗

**Comment by kksi0227** [comment]
Can you write a corresponding Demo

**Comment by Bracewind** [comment]
I suppose it depends on your platform, here are the step for C#
You have to write a xml file describing your Address Space (see https://opcua.rocks/custom-information-models/)
Then add a bat command to compile your file, for me it is basically

`CALL PublishModel OpcUaCustomModel  CUSTOM %1 %2 ` 

that I added to the Step 1 of the BuildStandardTypes.bat file
the OpcUaGemModel is the name of my xml file located in the ModelCompiler\Design.v104 folder

Then all the files will be generated in a folder outside this project called nodesets in CUSTOM folder (Same name that I put in the CALL command above)

If you want to use it properly, you have to create a bat file that is a little more complex.

**Comment by mpostol** [comment]
@kksi0227 you don't have to bother with the manual edition of the XML files. I have just released the new version 4.3 of the Address Space Model Designer (ASMD). In this release, many bugfixes have been applied. The  [OPCFoundation/UA-ModelCompiler][OPC.UA.ModelCompiler] is embedded as a plug-in to build a solution (check out the video [**ASMD - How to Build Solution**][CAS.VideBuild] to get started using an embedded example). 

Check out the new version and let me know how it works for you. This software is available here:

[https://github.com/mpostol/ASMD/releases/tag/4.3.0](https://github.com/mpostol/ASMD/releases/tag/4.3.0)

The ASMD Designer is a powerful tool, which allows creating, displaying, and editing OPC Unified Architecture models compliant with the OPC Unified Architecture Address Space (Part 3) and Information Model (Part 5) concepts. The tool is created for developers and engineers, for professionals and beginners. It is maintained as the open-source software (OOS) available at

[mpostol/ASMD](https://github.com/mpostol/ASMD)

Check it out to learn how it could help design OPC UA Information Model definitions. I hope, this article is useful to learn how to deploy IM.

[Information Models Development](https://commsvr.gitbook.io/ooi/semantic-data-processing/informationmodelsdevelopment)

## How to be involved

I am a researcher who is passionate about applying knowledge and experience in building a machine-centric global village. Let's build it with you and for you. To join our effort and create an organization context I have launched the [**Object-Oriented Internet Partnership Program**](https://github.commsvr.com/AboutPartnershipProgram.md.html).

> Consider joining as a sponsor, contributor, or end-user. Details are covered by the section [**How to be involved**](https://github.commsvr.com/AboutPartnershipProgram.md.html#how-to-be-involved)
>
> Your participation is needed to make sure the work will continue as expected.

## How to get started

### Installation

Download and run the file `UA.ModelDesigner.exe` to unzip the content to the selected folder and create an icon on the desktop. The application will run after unpacking. To restart the application you may use the icon on the desktop or double click the application file `<target>\UA.ModelDesigner\OOI.UA.ModelDesigner.exe`, where \<target\> is the already folder selected during the installation. To uninstall the software and embedded example simply delete the \<target\> folder and the icon.

> Note: The self-extracting zip file and the main application is not code-signed. The unsigned executable maybe not allowed by your company IT policy. The installer package containing signed stuff is on the project road map mpostol/ASMD#89. Further development planning is based on the sponsors' priorities.

### Opening the embedded example

Check out the section [How to open an example](https://github.com/mpostol/ASMD#how-to-open-an-example) in the project documentation or video [**OPC UA Information Model How to Create Instances**][CAS.VideoInstances].

## See Also

### Documentation

- [OPC UA Address Space Model Designer Help][github.MD]
- [Mariusz Postol. Address Space and Address Space Model](https://commsvr.gitbook.io/ooi/semantic-data-processing/addressspaceaddressspacemodel)
- [OPC UA Address Space Model Designer][CAS.ASMD]
- [ReferenceApplication Producer - Boilers Set Simulator][boiler]
- [Companion Specification - Information Model for Analyzers][ADI]
- [Information Models Development][IMD]
- [ASMD releases page][REL]
- [OPC 10020 - UA for Analyzer Devices (ADI), OPC Foundation Rel 1.1a, 2015][ADI]
- [OPCFoundation/UA-ModelCompiler][OPC.UA.ModelCompiler]

### Video

- [**OPC UA Information Model How to Create Instances**][CAS.VideoInstances] - The main aim of this movie is to demonstrate how to use a tool - the Address Space Model Designer to design OPC UA Information Model and instantiate OPC UA Address Space for selected well-known Boiler example.
- [**ASMD - How to Build Solution**][CAS.VideBuild] - How to get started using an embedded example.
- [Introduction to OPC UA Address Space modeling using CAS Address Space Model Designer; Video][CAS.MZASMDIntro]

[CAS.MZASMDIntro]:https://www.youtube.com/watch?v=pYOQA4atlRI&feature=youtu.be
[OPC.UA.ModelCompiler]:https://github.com/OPCFoundation/UA-ModelCompiler
[REL]: https://github.com/mpostol/ASMD/releases
[boiler]: https://commsvr.gitbook.io/ooi/reactive-communication/referenceapplication/simulator.boiler#informal-model-of-boiler
[ADI]: https://commsvr.gitbook.io/ooi/semantic-data-processing/informationmodelsdevelopment/companionspecificationinformationmodelfforanalyzers
[IMD]: https://commsvr.gitbook.io/ooi/semantic-data-processing/informationmodelsdevelopment
[ADI]:https://opcfoundation.org/developer-tools/specifications-opc-ua-information-models/opc-unified-architecture-for-analyzer-devices-adi/
[CAS.ASMD]:https://commsvr-com.github.io/Documentation/ModelDesigner
[OPENXML]:https://github.com/OfficeDev/Open-XML-SDK
[DEPGraph]:https://github.com/mpostol/ASMD/network/dependencies
[CAS.VideoInstances]:https://youtu.be/LvGHl-hRwZw
[CAS.VideBuild]:https://youtu.be/y3tndTA7YYo
[commserver]: http://www.commsvr.com/
[migration2os]: https://github.com/commsvr-com/migration2os
[migration2osProj]: https://github.com/orgs/commsvr-com/projects
[OOIBookToC]: https://commsvr.gitbook.io/ooi/TableOfContent.md#reactive-communication
[ConfigEditor]: https://github.com/mpostol/OPC-UA-OOI.ConfigEditor
[OOI]: https://github.com/mpostol/OPC-UA-OOI
[github.MD]:https://commsvr-com.github.io/Documentation/ModelDesigner
