### ISSUE TITLE
NodeId of type and instances are the same

### ISSUE THREAD

**Issue by Bracewind** [OPCFoundation/UA-ModelCompiler#56]
Hello everyone

I use the model compiler to create dynamically an object from a generated type.
From what I understood, if I create a type in the xml, let's say EquipmentServiceType, the software automatically generates a c# class named EquipmentServiceState that will be used to create an instance of the object.
When I try to use it, the EquipmentServiceType node in the Address Space and the object EquipmentServices that have EquipmentServiceState as typeDefinition have the same NodeId.

Here is the code I wrote:
` 

         var equipmentService = new EquipmentServiceState(null);
        // The equipment service type node has a NodeId of 1048, I checked before

         // nodeId not given yet
        equipmentService.Create(SystemContext, null, new QualifiedName("Equipment Services", NamespaceIndex), null, true);
        // if i check the nodeid of the equipment service, it is also 1048
        
        // Add references to the node so that it can be seen in the Address Space
        IList<IReference> references = null;

        if (!externalReferences.TryGetValue(Opc.Ua.ObjectIds.ObjectsFolder, out references))
        {
          references = new List<IReference>();
          externalReferences[Opc.Ua.ObjectIds.ObjectsFolder] = references;
        }

        equipmentService.AddReference(ReferenceTypeIds.Organizes, true, Opc.Ua.ObjectIds.ObjectsFolder);
        references.Add(new NodeStateReference(ReferenceTypeIds.Organizes, false, equipmentService.NodeId));

        // store it and all of its children in the pre-defined nodes dictionary for easy look up.
        AddPredefinedNode(SystemContext, equipmentService);`

What did I do wrong ?

**Comment by opcfoundation-org** [comment]
The best place to start is a working sample:
https://github.com/OPCFoundation/UA-.NETStandard-Samples/tree/master/Samples/Opc.Ua.Sample/Boiler
