### ISSUE TITLE
BuildStandardTypes.bat raises an error

### ISSUE THREAD

**Issue by eoursel** [OPCFoundation/UA-ModelCompiler#59]
At the '_Building model Provisioning_' stage
  

Looking for **OpcUaProvisioningModel**. Can't find it in Github in the Design folder. 

Regards

**Comment by benkinooby** [comment]
@eoursel if you look at the commits [1] you will see that OpcUaProvisioningModel.xml was added by @randy-armstrong  [2] but then got removed two commits / one day later [3] by @opcfoundation-org.

You can temporarily restore the files by reapplying the commit of @randy-armstrong 
`git cerry-pick 19c669ec9c63ef05e7b12483ff97a90517a7a63d` 

Afterwards, BuildStandardTypes.bat will execute without error.

@opcfoundation-org what was your rationale for removing OpcUaProvisioningModel.xml in [3] ?

[1] https://github.com/OPCFoundation/UA-ModelCompiler/commits/master
[2] https://github.com/OPCFoundation/UA-ModelCompiler/commit/19c669ec9c63ef05e7b12483ff97a90517a7a63d
[3] https://github.com/OPCFoundation/UA-ModelCompiler/commit/3754f9bb141b33d0f2a32cad984795295a060782

**Comment by opcfoundation-org** [comment]
Unreleased material does not get checked into the public repo. The batch script had a reference should have been removed.
I need to figure out how to permanently delete mistaken commit.

**Comment by opcfoundation-org** [comment]
Squashed the commit and fixed the batch file.

**Comment by benkinooby** [comment]
Confirmed. No issues at master branch commit id c75b5bfe94b8adb448d54cabe7d4ad170adb412b

Thank you very much for the fix!
