### ISSUE TITLE
help text inconsistent

### ISSUE THREAD

**Issue by benkinooby** [OPCFoundation/UA-ModelCompiler#61]
The built in help text at 
https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/ModelCompiler/HelpFile.txt
seems to be inconsistent or incomplete.

Example command indicates possible use of `-oi` which is not explained. In what case is `-oi` preferable over `-o`?

Example command indicates possible use of `-oe` which is not explained. What does it do?

No explanation for `-ansic`

No explanation for `-stack`

No explanation for `-useXmlInitializers`

`-version` According to the example document in the help, `-version` seems to be an optional flag. Which values is the default value, if the flag is not set?

Kind regards

**Comment by opcfoundation-org** [comment]
Manually added to:
https://github.com/OPCF-Members/UA-ModelCompiler/commit/77e58b52873a31922fea57ca5d7acebe2432e982
Will merge to public repo in the next week or so.
