### ISSUE TITLE
How to overwrite methods from BaseType

### ISSUE THREAD

**Issue by DADev99** [OPCFoundation/UA-ModelCompiler#66]
Is it possible to overwite a method from a BaseType? Let's say I have an object who's base type is TemporaryFileTransferType, can I overwrite it's method GenerateFileForRead?

```
  <ObjectType SymbolicName="MyNS:SubTypeObj" BaseType="ua:TemporaryFileTransferType" >
    <Children>
      <Method SymbolicName="MyNS:GenerateFileForRead" TypeDefinition="MyNS:GenerateFileForReadMethodType" ModellingRule="Mandatory">                
      </Method>   
    </Children>    
  </ObjectType>
```

I would like to do this so I can provide a method definition like so:

```
  <Method SymbolicName="MyNS:GenerateFileForReadMethodType">
    <InputArguments>
      <Argument Name="GenerateOptions" DataType="ua:String"></Argument>
    </InputArguments>
    <OutputArguments>
      <Argument Name="FileNodeId" DataType="ua:NodeId"></Argument>
      <Argument Name="FileHandle" DataType="ua:UInt32"></Argument>
      <Argument Name="CompletionStateMachine" DataType="ua:NodeId"></Argument>      
    </OutputArguments>
  </Method>
```

But when I try to do this, in the generated NodeSet2, the MethodDeclarationId is the id for the GenerateFileForRead in the TemporaryFileTransferType.

The reason for asking is because the machine vision companion specification asks to overwrite these methods and I would like to know how this could be done through a UA Model Design

**Comment by opcfoundation-org** [comment]
Not supported at this time.
