### ISSUE TITLE
Docker image do not build

### ISSUE THREAD

**Issue by eoursel** [OPCFoundation/UA-ModelCompiler#69]
Hi all, i did not succeed to build the docker image. 

` > [6/11] RUN msbuild "ModelCompiler Solution.sln" /t:Build /p:Configuration=Release /p:TargetFrameworkVersion="v4.5":
#11 0.363 Microsoft (R) Build Engine version 16.6.0 for Mono
#11 0.363 Copyright (C) Microsoft Corporation. All rights reserved.
#11 0.363
#11 0.371 Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
#11 0.579 Build started 11/28/2020 17:34:15.
#11 0.974 Project "/tmp/app-build/ModelCompiler Solution.sln" on node 1 (Build target(s)).
#11 0.976 ValidateSolutionConfiguration:
#11 0.976   Building solution configuration "Release|Mixed Platforms".
#11 1.233 Project "/tmp/app-build/ModelCompiler Solution.sln" (1) is building "/tmp/app-build/ModelCompiler/UA Model Compiler.csproj" (2) on node 1 (default targets).
#11 1.233 PrepareForBuild:
#11 1.233   Creating directory "/tmp/app-build/Bin/Release/".
#11 1.234   Creating directory "/tmp/app-build/build/obj/AnyCPU/Release/UA Model Compiler/".
#11 1.275   It was not possible to find any installed dotnet SDKs
#11 1.275   Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
#11 1.275       https://aka.ms/dotnet-download
#11 1.391 /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1675,5): error : Project '../Stack/Stack/Opc.Ua.Core/Opc.Ua.Core.csproj' targets 'net462;netstandard2.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.5'. [/tmp/app-build/ModelCompiler/UA Model Compiler.csproj]
#11 1.409 Done Building Project "/tmp/app-build/ModelCompiler/UA Model Compiler.csproj" (default targets) -- FAILED.
#11 1.448   It was not possible to find any installed dotnet SDKs
#11 1.448   Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
#11 1.448       https://aka.ms/dotnet-download
#11 1.545 Project "/tmp/app-build/ModelCompiler Solution.sln" (1) is building "/tmp/app-build/Stack/Stack/Opc.Ua.Core/Opc.Ua.Core.csproj" (3:2) on node 1 (default targets).
#11 1.545 Project "/tmp/app-build/Stack/Stack/Opc.Ua.Core/Opc.Ua.Core.csproj" (3:2) is building "/tmp/app-build/Stack/Stack/Opc.Ua.Core/Opc.Ua.Core.csproj" (3:3) on node 1 (Build target(s)).
#11 1.545 PrepareForBuild:
#11 1.545   Creating directory "bin/Release/net462/".
#11 1.546   Creating directory "obj/Release/net462/".
#11 1.589 /usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/tmp/app-build/Stack/Stack/Opc.Ua.Core/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/tmp/app-build/Stack/Stack/Opc.Ua.Core/Opc.Ua.Core.csproj]
#11 1.595 Done Building Project "/tmp/app-build/Stack/Stack/Opc.Ua.Core/Opc.Ua.Core.csproj" (Build target(s)) -- FAILED.`

**Comment by opcfoundation-org** [comment]
There is a pull request that may fix this:
https://github.com/OPCFoundation/UA-ModelCompiler/pull/62

**Comment by opcfoundation-org** [comment]
Stale issue.
