### ISSUE TITLE
How could I create the input file that conforms to the schema defined in UA Model Design.xsd

### ISSUE THREAD

**Issue by ggokka** [OPCFoundation/UA-ModelCompiler#7]
Where is the UA Model Design Tool?

**Comment by SparhawkSoftware** [comment]
This github called Opc.Ua.ModelCompiler which processes UA Model Design XMLs.

**Comment by Hanky27** [comment]
And how can one create/edit UA Model Design XMLs???

**Comment by mpostol** [comment]
Have a look on comments following 

Cant Compile Models using UANodeSet.xsd schema #5
