### ISSUE TITLE
ModelDesign.xsd availability in `opcfoundation.org` domain

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-ModelCompiler#72]
My concern is if the `ModelDesign.xsd` is also published in the official "opcfoundation.org" domain. Previously it was available for download from

<http://opcfoundation.org/UA/ModelDesign.xsd>

Now the link is broken.

It is a very important document for the designers to exchange OPC UA Information Model as a  "source code", but not as an export form Address Space using UANodesSet2.xsd schema.  UANodesSet2.xsd files are generated and are very hard to edit.

![Screen Shot 27 01 2021 at 12 54](https://user-images.githubusercontent.com/11937915/105988566-1e0af300-60a0-11eb-9461-cfa6e0a38123.png)

**Comment by opcfoundation-org** [comment]
Fixed.

**Comment by mpostol** [comment]
@opcfoundation-org , OK, redirection works, but it doesn't mean that the document is published in `opcfoundation.org` domain.  Consider using `GitHub pages` and `Custom domain`. 

Anyway, it works for me. I assume it is still a custom schema (not standardized) and not versioned, so doesn't matter where it is published. Because of the problem with licensing of the software, it must be considered independent DSL (Domain Specific Language) to describe OPC UA Information Model - but it is out of the scope of this discussion.

Thanks,
