### ISSUE TITLE
Describe the role of the Design.v103 and Design.v104 folders

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-ModelCompiler#73]
I am trying to figure up how to harmonize my work and derive as much as possible from this repository to promote the reusability of the effort covered by the MIT license. The mentioned folders don't have any description as far as I know.

I hope that the OPC Foundation as a nonprofit organization should promote the democratization of the common community effort to leverage OPC UA adaptation.  My point is that comprehensive documentation is a vital factor in this respect.

I can prepare a pr with the appropriate explanation provided there is a chance it will be merged in a few weeks but not in a few years.

**Comment by opcfoundation-org** [comment]
Design* folders contain the source files for different versions of the Core specification.
These source files are used to generate the code that appears in the branch of the same name.
e.g.: https://github.com/OPCFoundation/UA-Nodeset/tree/v1.04

**Comment by mpostol** [comment]
To be sure, I understand that they are used to keep track of versioning instead of the tag concept used by GitHub repositories?

Have you considered using [Semantic Versioning 2.0.0](https://semver.org/)?

**Comment by opcfoundation-org** [comment]
The NodeSet version is the same as the specification version. Changing the major or minor version after an errata is not an option.

**Comment by mpostol** [comment]
The NodeSet ? OK, take it easy.
