### ISSUE TITLE
OPC UA Stability

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-ModelCompiler#75]
We can learn over and over that the OPC UA is not just a standard but much more, i.e. it is a technology.  From technology, we shall expect continuous improvement, but stability for a  standard is demanded. Working on OPC UA Information Models development I have compared available versions for the `StandardTypes.xml` in folder `Design.v104`and the result is as follows.

```txt
5321 same line(s)
3 unimportant left orphan line(s)
68 unimportant right orphan line(s)
4 unimportant difference line(s)
6 important left orphan line(s)
491 important right orphan line(s)
132 important difference line(s)

137 difference section(s)
```

Provided that it is a source file for all "defined types" in the spec my concern is how to track the changes covered by the common release 1.04 (**minor** subversion). How to adapt the spec if in every few months hundred of modifications related to the core concept must be accommodated. How to prove that all modifications are backward compatible?

Can you confirm or explain my observation?

For `UA Defined Types.xml` (next fundamental for the spec file) the diff result is as follows:

```txt
6619 same line(s)
955 important left orphan line(s)
518 important right orphan line(s)
731 important difference line(s)

445 difference section(s)
```

**Comment by mpostol** [comment]
Not sure about the folder's role but I have also compared the files `StandardTypes.xml ` located in  `Design.v104` and in `Design.v103`. The result is as follows: 

```txt
2822 same line(s)
21 unimportant left orphan line(s)
278 unimportant right orphan line(s)
16 unimportant difference line(s)
103 important left orphan line(s)
2823 important right orphan line(s)
77 important difference line(s)

125 difference section(s)
```

**Comment by mpostol** [comment]
After comparing the number of items that are to be exposed in the Address Space between 1.04 and 1.04.7 we are getting the following table:

| Part  | 1.04 2016-12-31 | 1.04.7 2020-07-1T `UA-1.04.7-2020-07-15` |
| :---: | :-------------: | :--------------------------------------: |
|   0   |       20        |                    12                    |
|   1   |        0        |                    0                     |
|   2   |        0        |                    0                     |
|   3   |       90        |                   101                    |
|   4   |       53        |                    55                    |
|   5   |       169       |                   209                    |
|   6   |        0        |                    0                     |
|   7   |        0        |                    0                     |
|   8   |       19        |                    22                    |
|   9   |       58        |                    65                    |
|  10   |        6        |                    8                     |
|  11   |       15        |                    16                    |
|  12   |       13        |                    26                    |
|  13   |       38        |                    38                    |
|  14   |       76        |                   146                    |
|  15   |        0        |                    0                     |
|  17   |        0        |                    0                     |
|  19   |        0        |                    2                     |
| Total |       557       |                   708                    |

The 1.04.7 suggests that it is only a patch, but according to the [Semantic Versioning 2.0.0](https://semver.org/#semantic-versioning-200) standard, it looks like a backward-incompatible new release (API changed) - we have 150+ new items in the server Address Space.

The detailed methodology you can learn from mpostol/OPC-UA-OOI#502

**Comment by opcfoundation-org** [comment]
@mpostol all changes to released nodeset require a mantis issue and an errata.
The changes occur as people find issues/inconsistencies with the NodeSet that need to be fixed.

Before any change is published there is a 30 day review period to give people a chance to raise issues:
https://opcfoundation.org/developer-tools/specifications-unified-architecture/specification-release-candidates-for-review/

That said, the OPC Foundation has been investing in numerous automated tools designed to find errors in NodeSets before they are published.  They tools will greatly reduce the number of errata required for released NodeSets in the future.

**Comment by mpostol** [comment]
@opcfoundation-org,  As an independent consultant my concerns are as follows: 

- standard stability
- run-time/design-time interoperability (e.g. IM exchange)
- run-time/design-time compliance testing

To fulfill my job I need

- modifications tracking and versioning
- standard (mandatory parts) validation
- to know how to deploy spec

Now I am working on OPC UA Information Model compliance testing. An important part of this work is a semantic diff of the XML stuff. In this context is

 - **Can you confirm my findings?**

The reason for that is not so important, but after 10 years on the market, there are still fundamental ..... 

My next concern is the versioning rules. So my next question is:

- **Can you confirm that all the reported modifications are backward compatible in the context of interoperability and compliance testing?**

Do you really think that 150+ new items in the server Address Space may be recognized as backward compatibility?

As you know I am aware of the rules, but maybe there is something wrong with the rules?

**Comment by opcfoundation-org** [comment]
> Can you confirm that all the reported modifications are backward compatible in the context of interoperability and compliance testing?

Every effort is made to ensure backward compatibility and, in some cases, changes are prototyped to verify backward compatibility. However, in some cases, the NodeSet did not match the specification so the NodeSet was changed. But this generally occurs with a feature that was not widely used and there is no compliance test. If a difference exists when there is a compliance test then we usually change the specification to match the NodeSet (this is generally the default assumption).

> Do you really think that 150+ new items in the server Address Space may be recognized as backward compatibility?

Purely additive changes have no effect on backward compatibility.  Simply adding a optional Property to an ObjectType can trigger a large number of non-critical differences in the NodeSet. So running a tool to count the number of differences does not give you an accurate picture of the number of real changes or their significance.

If you have specific changes that are a concern then we can discuss them.

**Comment by mpostol** [comment]
To talk about compliance you must say: `yes/no" for sure. But you are using `Every effort is made`, `n some cases`, ` this generally occurs`, `feature that was not widely used `, `there is no compliance test`, ` we usually change`, ` a large number of non-critical differences `, etc. How to measure `effort`, what ``n some cases` actually means, etc in the context of the specification (a form of contract between vendors investing a lot of money to be compliant). Saying that how to prove that independent certification labs will guarantee the same results? How to develop a product if the environment is not stable?  Translating these concerns to decision-makers' language, we are saying probably you will get your money back, provided that ....., in some cases, but ..., etc.

We are aware of the necessity of expandability and bug fixing, but there must be a trade-off,  There are many solutions (including inheritance) to address that. 

Generally speaking, talking about the tracing changes we have the following possibilities:

1. text diff
2. XML diff
3. XML semantic dif
4. XML semantic dif excluding `feature that was not widely used `, `non-critical differences `, etc. 

Following that my questions are:

1. Do you know a tool that meets the requirement stated in 4
2. Do you know implementable ruls that can be used to deploy a diff tool according to 4

Unfortunately, in a group of experts, now we are discussing if the `namespaceIndex` part of `BrowseName` (`QualifiedName`) is optional or not in the UANodeSet file, and what if it is optional.  Maybe you can point out the place in the spec where it is clearly stated. It is a fundamental attribute of Node and in general Address Space concept.

**Comment by opcfoundation-org** [comment]
> We are aware of the necessity of expandability and bug fixing, but there must be a trade-off, There are many solutions (including inheritance) to address that.

And all of those options are explored by the WG with each issue that is raised. Breaking changes are avoided as much as possible. In the rare exceptions, the change is for a type that could not be used in its current form because of an error.

If you have specific examples of changes that caused problems for you then please post them. The WG needs this feedback so can take it into account for future decisions.

Unfortunately, abstract concerns about the number of text changes in the document does not provide information that would allow the WG to improve its processes.

**Comment by mpostol** [comment]
Let me recall my problems:

- stability - how to prove that the standard is stable
- interoperability - how to prove that the IM is compliant with the specification
- track changes - how to distinguish important and unimportant IM changes
- compliance - design-time multi-vendor exchange of IM 

For me, they are not abstract ones. For my job, all of them appear to be fundamental. I know that it is much easier to discuss the syntax of XML and the position of dots.  I had been doing it for years with a minor result. Now, I was not asked about it.

Anyway, keep it easy. I have got the precise answer. It seems to me that it is all that we as the technical experts can do at this time.
Best regards,
Mariusz
