### ISSUE TITLE
.BAT files are referencing v105 version instead of v104

### ISSUE THREAD

**Issue by kratochvilt** [OPCFoundation/UA-ModelCompiler#78]
Following these example generation steps in README.md:

> 1. Clone the repository and then build the source in Visual Studio 2015, in Release mode.
> 2. Open a Command prompt and then launch the BuildStandardTypes.bat
> 3. After the script completes, navigate to the .\Published folder to view the output.
> 4. Optionally, modify the BAT file and specify the location of your UA Stack(s) to automatically copy the generated files.

When launching BuildStandardTypes.bat, this error is throwed:
`The design file does not exist: .\ModelCompiler\Design.v105\StandardTypes.xml
at ModelCompiler.Program.ProcessCommandLine2(List1 tokens) in C:\***\UA-ModelCompiler\ModelCompiler\Program.cs:line 405`

Problem is that inside **BuildStandardTypes.bat** and **PublishModel.bat** are lines referencing **v105** version, that does not exists in ModelCompiler folder.

To get it working, i had to edit string v105 to v104 in these files:
https://github.com/OPCFoundation/UA-ModelCompiler/blob/35d4d3d906582a6da1891450c1c1d73995d45bc0/BuildStandardTypes.bat#L17-L18
https://github.com/OPCFoundation/UA-ModelCompiler/blob/35d4d3d906582a6da1891450c1c1d73995d45bc0/PublishModel.bat#L18

Also, according to step 3, no .\Published folder is created.

**Comment by opcfoundation-org** [comment]
Fixed.

**Comment by opcfoundation-org** [comment]
Closed since no further comments from posters.
