### ISSUE TITLE
Unistall unused NuGet packages

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-ModelCompiler#79]
The project `UA Model Compiler` refers to a bunch of unused NuGet packages, e.g. `OPCFoundation.NetStandard.Opc.Ua.Client`.

**Comment by opcfoundation-org** [comment]
NuGet packages have been cleaned up in next version.

**Comment by mpostol** [comment]
Not sure `have been cleaned` or `will be cleaned`

**Comment by opcfoundation-org** [comment]
The new version is available here:
https://github.com/OPCF-Members/UA-ModelCompiler

**Comment by mpostol** [comment]
@opcfoundation-org  the link is broken for me. From your answer, I can learn that providing any feedback for this repository doesn't make any sense, because my comments are used to improve the code that is unavailable for me. To be honest, I am reporting problems for this open-source but not for the organization.

**Comment by opcfoundation-org** [comment]
Updated README to explain how the release process works and how issues reported here are handled.

**Comment by mpostol** [comment]
According to the repository rules all feedback is applied to a private repository, hence I am no longer a willing helper to contribute to further development of the code. I am transferring this issue to my public fork mpostol/UA-ModelCompiler#9 where the modification will be applied directly and available for the public immediately. Further questions and proposals - you may have - should be provided using the [discussion panel](https://github.com/mpostol/UA-ModelCompiler/discussions) of the fork or by adding comments to the mentioned issue. Let's work out it with you and for you.

Close it with `wontfix` reason.
