### ISSUE TITLE
Remove .gitmodules - dependency on UA-.NETStandard repository

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-ModelCompiler#80]
The project `UA Model Compiler` uses NuGet packages but the repository still refers to the `url = https://github.com/OPCFoundation/UA-.NETStandard.git`.

**Comment by opcfoundation-org** [comment]
Not clear why this is a problem.
The submodule is needed for testing and development.

**Comment by mpostol** [comment]
According to the repository rules all feedback is applied to a private repository, hence I am no longer a willing helper to contribute to further development of the code. I am transferring this issue to my public fork mpostol/UA-ModelCompiler#7 where the modification will be applied directly and available for the public immediately. Further questions and proposals - you may have - should be provided using the [discussion panel](https://github.com/mpostol/UA-ModelCompiler/discussions) of the fork or by adding comments to the mentioned issue. Let's work out it with you and for you.

Cloe it with `wontfix` reason.
