### ISSUE TITLE
Help with a simple example

### ISSUE THREAD

**Issue by om327** [OPCFoundation/UA-ModelCompiler#87]
Hello, I'm trying to build a very simple OPC UA console server with only a few nodes and maybe one method. I've managed to clone and run the UA-.NET ConsoleReferenceServer and deploy it in a docker container but i'm strugging to understand how to change the deafult nodes and I can't seem to find the xml where these are saved so i could change them? 

I'm assuming it also wont be as simple as manually changing the names and data types so i'll need to use the UA-ModelCompiler. I'm really sorry but I don't understand how to use it based on the instructions in the README or where I need to save the output so that the consoleReferenceServer i'm using as a base will use these node names rather than the default values where it is getting these from? 

I tried to follow the the following guide https://opcfoundation.github.io/UA-.NETStandard/help/index.htm#server_development.htm but is out of date (2015) and no longer works or mirrors whats in the UA-.NETStandard repository...is it possible to explain what I need to do to add my own nodes to the ConsoleReferenceServer? 

Really apprechiate any help!

**Comment by opcfoundation-org** [comment]
Try this sample:
https://github.com/OPCFoundation/UA-.NETStandard-Samples/tree/master/Workshop/Boiler

**Comment by om327** [comment]
Hello,

Thank you for getting back to me!

I’ve tried to understand what’s going on in the examples but there is just so much code its very hard to see what’s import and how they actually work. Since the different examples have different models and how they make their models its hard to compare and contrast.

Initially I’m attempting to replicate the very simple server that is supplied by ProSys where they only have a couple of nodes that generate some random numbers. This is what I did using OPC UA for NodeJS - Unfortunately NodeJS is very sluggish!

Another reason for using .NET is, I also want to re-use some code I made using LabVIEW by exporting the VIs as .dlls and using them to connect to my hardware.

Randy very kindly answered one of my questions about how the examples generate the nodes but also confused me even more since there are three ways, static, dynamic and virtual. Unfortunately there isn’t much documentation other than how to build these examples in the Git Hub pages. Were these used in a tutorial or part of a workshop where a teacher leader the class – if so was this filmed or are there any lecture notes?

I’m trying to find a really simple example that has one node and one method to really cut down of the amount of code. The boiler example is very daunting for a newbie coder like me and is showing too many features which would be very useful to someone who already codes routinely in OPC UA and .NET.

The other problem I have, is understanding when you should use a server and when you should use a client…there seems to be conflicting articles about this?

Should the protocols for controlling the instrument be on the server side as part of a method or on the client side in a state machine? If so, should each piece of equipment have its own server which is then connected by a aggregate server or should there be just one server with individual pieces of equipment being controlled by their own client. If this is the case, should the client hold the protocols and connect to the equipment with the server just providing values from the client for other clients?

Really appreciate the help!

Many thanks,
Ollie
