### ISSUE TITLE
Upgrade to .NET 5.0 In Pipeline

### ISSUE THREAD

**Issue by opcfoundation-org** [OPCFoundation/UA-ModelCompiler#88]
The ModelCompiler is being upgraded to use .NET 5.0.

Please post here is you have concerns/issues/requirements.

**Comment by mregen** [comment]
In addition it would be great to have prebuilt docker images...

**Comment by koepalex** [comment]
@opcfoundation-org I would wait until November when .NET 6 (LTS) is released and upgrade to the LTS version directly.

**Comment by opcfoundation-org** [comment]
> 
> @opcfoundation-org I would wait until November when .NET 6 (LTS) is released and upgrade to the LTS version directly.

I assume the delta from 4.6 => 5.0 is greater than 5.0 => 6.0 and most of that work is already done.
