### ISSUE TITLE
DataTypeDefinition IsOptional fields default to true, was false

### ISSUE THREAD

**Issue by mregen** [OPCFoundation/UA-ModelCompiler#89]
Compared to previous versions of the ModelCompiler output, now the default structure definition sets the IsOptional field by default to true. However according to spec the default should be false.

see also : https://github.com/OPCFoundation/UA-.NETStandard/issues/1476

![ModelCompilerStructureOutput](https://user-images.githubusercontent.com/7962757/130419327-004de9fe-f5f7-4a65-821e-a2903310229a.png)

**Comment by opcfoundation-org** [comment]
Pushed fix to 
https://github.com/OPCF-Members/UA-.NETStandard-Prototypes/commit/42098670e197c02cbff71b91d7a00aedc50e1a92

The ModelDesign.xsd now supports a default value for DataType Fields. 
This allows modellers to explicitly specify false as a default value for boolean fields.
Other types are not supported yet.
