### ISSUE TITLE
Combining OPC UA - DI NodeSet with OPC UA PubSub NodeSet defined in IoT Gateway - OPC UA Publisher github repo

### ISSUE THREAD

**Issue by JayeshThamke** [OPCFoundation/UA-ModelCompiler#9]
Hi,
I recently am experimenting for my university project on OPC UA DI nodeset and I wonder if I could give new feature like OPC UA PubSub to my UA Server application. I want to integrate both NodeSet to make my UA Server PubSub enabled. However, for that as per my knowledge I need to prepare a new NodeSet which  collaborates both DI and PubSub NodeSets. How can I do this collaboration with UA Model-Compiler? Thanks and please correct me if I misunderstood the technology. 

- Jayesh

**Comment by opcfoundation-org** [comment]
The Part 14 information is part of the base UA NodeSet now,

That said, you should be able to load as many NodeSets as you need into the Server namespace.
