### ISSUE TITLE
Generated C# code for structure with optional fields is not quite right

### ISSUE THREAD

**Issue by mregen** [OPCFoundation/UA-ModelCompiler#92]
Hi @opcfoundation-org, I don't see in the code where the C# Modelcompiler generated code is fixed.

When I run this description through ModelCompiler:
```
<opc:DataType SymbolicName="ComplexTypeWithOptionsType" BaseType="ua:Structure">
    <opc:Fields>
      <opc:Field Name="X" DataType="ua:Double" IsOptional="true" />
      <opc:Field Name="Y" DataType="ua:Double" IsOptional="true" />
      <opc:Field Name="Z" DataType="ua:Double" IsOptional="true" />
    </opc:Fields>
  </opc:DataType>
```

the generated C# code:

```
       /// <summary cref="IEncodeable.Encode(IEncoder)" />
        public virtual void Encode(IEncoder encoder)
        {
            encoder.PushNamespace(ComplexTypesInterop.Namespaces.ComplexTypesInterop);

            encoder.WriteDouble("X", X);
            encoder.WriteDouble("Y", Y);
            encoder.WriteDouble("Z", Z);

            encoder.PopNamespace();
        }
```

I'd expect generated code like this for structure with optional fields:

```
       /// <summary cref="IEncodeable.Encode(IEncoder)" />
        public virtual void Encode(IEncoder encoder)
        {
            encoder.PushNamespace(ComplexTypesInterop.Namespaces.ComplexTypesInterop);

            encoder.WriteUInt32("EncodingMask", m_bitMask);
            if ((m_bitMask & 1)!=0) encoder.WriteDouble("X", X);
            if ((m_bitMask & 2)!=0) encoder.WriteDouble("Y", Y);
            if ((m_bitMask & 4)!=0) encoder.WriteDouble("Z", Z);

            encoder.PopNamespace();
        }

```

_Originally posted by @mregen in https://github.com/OPCFoundation/UA-ModelCompiler/issues/48#issuecomment-916217121_

**Comment by elliot-gawthrop** [comment]
Hi @mregen, would you expect this solution to work for other encoding schemes where EncodingMask is not a UInt32 (such as XML where it is a UInt64)?

**Comment by elliot-gawthrop** [comment]
The generated code also needs to expose a way to indicate that a field has not been set, such as making optional fields nullable.

**Comment by mregen** [comment]
> would you expect this solution to work for other encoding schemes where EncodingMask is not a UInt32 (such as XML where it is a UInt64)?

Technically the classes don't know about the underlying encoder/decoder. EncodingMask must be the same bit size across different encoding schemes, I guess UInt64 would be the right choice then.

**Comment by elliot-gawthrop** [comment]
> > would you expect this solution to work for other encoding schemes where EncodingMask is not a UInt32 (such as XML where it is a UInt64)?
> 
> Technically the classes don't know about the underlying encoder/decoder. EncodingMask must be the same bit size across different encoding schemes, I guess UInt64 would be the right choice then.

Yes it is strange that XML encoding scheme specifies the EncodingMask as UInt64, it's hard to imagine how it would be safe to rely on the upper 32 bits when there is the possibility of them being clipped in the binary encoding scheme. I wonder what the rationale for this was.

**Comment by opcfoundation-org** [comment]
The WG decided that 32 optional fields is more than enough (modellers can always create nested structures).
The unsignedLong in XML was error. It should have been unsignedInt.

**Comment by opcfoundation-org** [comment]
The member-only repo has a fix:
https://github.com/OPCF-Members/UA-ModelCompiler/blob/master/README.md

**Comment by opcfoundation-org** [comment]
Now part of public repository.
