### ISSUE TITLE
Broken link to UA Model Design.xsd

### ISSUE THREAD

**Issue by MurzynJ** [OPCFoundation/UA-ModelCompiler#97]
The hyperlink to UA Model Design.xsd in README.md is broken. The path has changed some time ago due to refactoring.

>The [UA Model Design.xsd](https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/ModelCompiler/UA%20Model%20Design.xsd) has more information about the schema itself.

**Comment by opcfoundation-org** [comment]
Fixed
