### ISSUE TITLE
Missing csvHelper

### ISSUE THREAD

**Issue by om327** [OPCFoundation/UA-ModelCompiler#99]
Hello, 

This maybe a VS version issue rather than a code one but i can't seem to build the executable in VS 2022. I've installed all the NuGet modules but the build appears to be missing some other libraries or can't find them? I've attampted to install the missing csvHelper separately but the error still persists?

Many thanks!
Ollie

![image](https://user-images.githubusercontent.com/64647451/144859446-5cfac27f-54af-4eca-895e-86a8bd7d77ed.png)

**Comment by om327** [comment]
After some tracking down missing pacakages i've managed to get the solution to build without withour errors but the .exe doens't open? Also the package size seems very small compared to tudtorial i'm following - it looks like this is being built with .net5.0 is that correct?

![image](https://user-images.githubusercontent.com/64647451/144869387-3000fd89-8c4c-4f97-becb-6b6d2c6786fd.png)

**Comment by opcfoundation-org** [comment]
Fixed the project references.
